'use client';

// ============================================================================
// CvPrintView — Print-optimised CV layout
// Triggered by window.print() — @media print CSS hides everything else
// ============================================================================

import type { Candidate } from '@/types/database';

interface CvPrintViewProps {
  candidate: Candidate;
}

export function CvPrintView({ candidate }: CvPrintViewProps) {
  const { cv_structured: s } = candidate;

  return (
    <div id="cv-print" className="hidden print:block print:fixed print:inset-0 print:bg-white print:text-black print:p-10 print:text-sm print:font-sans">
      {/* Header */}
      <div className="border-b-2 border-black pb-4 mb-6">
        <h1 className="text-3xl font-bold tracking-tight">{candidate.full_name}</h1>
        <div className="flex flex-wrap gap-4 mt-2 text-gray-600 text-sm">
          {candidate.email && <span>{candidate.email}</span>}
          {candidate.phone && <span>{candidate.phone}</span>}
          {candidate.location && <span>{candidate.location}</span>}
        </div>
        {candidate.seniority_level && (
          <p className="text-gray-500 text-sm mt-1">
            {candidate.seniority_level} · {candidate.years_of_experience ?? 0}+ years
          </p>
        )}
      </div>

      {/* Summary */}
      {s?.summary && (
        <Section title="Summary">
          <p className="text-gray-700 leading-relaxed">{s.summary}</p>
        </Section>
      )}

      {/* Skills */}
      {candidate.skills?.length > 0 && (
        <Section title="Skills">
          <p className="text-gray-700">{candidate.skills.join(' · ')}</p>
        </Section>
      )}

      {/* Experience */}
      {s?.experience && s.experience.length > 0 && (
        <Section title="Experience">
          {s.experience.map((exp, i) => (
            <div key={i} className="mb-4 last:mb-0">
              <div className="flex justify-between items-baseline">
                <h3 className="font-semibold">{exp.title}</h3>
                <span className="text-gray-500 text-xs">
                  {exp.start_date}{exp.end_date ? ` — ${exp.end_date}` : ' — Present'}
                </span>
              </div>
              <p className="text-gray-600 text-sm">{exp.company}</p>
              {exp.description && <p className="text-gray-700 mt-1 leading-relaxed">{exp.description}</p>}
              {exp.highlights && exp.highlights.length > 0 && (
                <ul className="mt-1 space-y-0.5">
                  {exp.highlights.map((h, j) => (
                    <li key={j} className="text-gray-700 pl-4 relative before:absolute before:left-0 before:content-['•']">{h}</li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </Section>
      )}

      {/* Education */}
      {s?.education && s.education.length > 0 && (
        <Section title="Education">
          {s.education.map((edu, i) => (
            <div key={i} className="mb-3 last:mb-0">
              <div className="flex justify-between items-baseline">
                <h3 className="font-semibold">{edu.degree}</h3>
                {edu.year && <span className="text-gray-500 text-xs">{edu.year}</span>}
              </div>
              <p className="text-gray-600 text-sm">{edu.institution}</p>
            </div>
          ))}
        </Section>
      )}

      {/* Languages */}
      {s?.languages && s.languages.length > 0 && (
        <Section title="Languages">
          <div className="flex flex-wrap gap-3">
            {s.languages.map((lang, i) => (
              <span key={i} className="text-gray-700">{lang.language} ({lang.level})</span>
            ))}
          </div>
        </Section>
      )}

      {/* Certifications */}
      {s?.certifications && s.certifications.length > 0 && (
        <Section title="Certifications">
          <ul className="space-y-0.5">
            {s.certifications.map((cert, i) => (
              <li key={i} className="text-gray-700 pl-4 relative before:absolute before:left-0 before:content-['•']">{cert}</li>
            ))}
          </ul>
        </Section>
      )}

      {/* Footer */}
      <div className="mt-8 pt-4 border-t border-gray-200 text-xs text-gray-400 text-center">
        Generated by MatchPoint AI
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-6">
      <h2 className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-2 border-b border-gray-200 pb-1">{title}</h2>
      {children}
    </div>
  );
}
